[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100

[deploy.env]
NODE_ENV = "production"
DATABASE_URL = "postgresql://postgres:LaVzarpyWoOBiRykBmgnpmHXpwxxyfDl@junction.proxy.rlwy.net:10109/railway" 